### ISSUE TITLE
Option to specify multiple permitted label values

### ISSUE THREAD

**Issue by Aldenar** [prometheus-community/prom-label-proxy#126]
I'm looking for a piece of software that would enforce a given label in PromQL queries, for which this project seems like the perfect candidate, with only one key issue: I need to be able to specify multiple possible / permitted values for a given label. 

As to my understanding, in the current state, prom-label-proxy only supports enforcing one value for a given label. Would it be possible to allow a list of permitted values to be specified instead?

E.g.: I'm trying to build a grafana-based graphing solution for many different clients, all instances of which share the same single Prometheus datasource.

All the queries of a given Grafana instance then have to contain a `host="*hostname*"` label, where a `*hostname*` is a hostname of one of the customers' servers. However, one customer more often than not runs more than a single server.

The way it could work is the `--value` parameter could take a comma-delimited list of permitted values. Allowing us to specify as many individual servers as the client operates, as well as `--default-value` for the default value of a label in case it wasn't present at all.

If the given label is present, but set to a different than one of the permitted values, it'd either get rewritten according to `--default-value` or return a 400 if ran with `--error-on-replace`

**Comment by dbluxo** [comment]
This PR might implement at least part of your requirements?: https://github.com/prometheus-community/prom-label-proxy/pull/115
