### ISSUE TITLE
Consider migrating to "github.com/efficientgo/core"

### ISSUE THREAD

**Issue by Rick-xuy** [prometheus-community/prom-label-proxy#138]
It seems that module `github.com/efficientgo/tools/core` has been [moved](https://github.com/efficientgo/tools/blob/main/README.md#note-core-module-from-this-repository-is-now-deprecated-and-move-to-standalone-repo-with-higher-compatibiltiy-guarantees-httpsgithubcomefficientgocore) to standalone repo [`github.com/efficientgo/core`](https://github.com/efficientgo/core). Original module `github.com/efficientgo/tools/core` is deprecated now. Is there any plan to migrate to `github.com/efficientgo/core`?

**Comment by simonpasquier** [comment]
@Rick-xuy feel free to contribute the PR :)

**Comment by Rick-xuy** [comment]
I submit a PR([#140](https://github.com/prometheus-community/prom-label-proxy/pull/140)) which tries to migrate to new module.
