### ISSUE TITLE
Tenant headers cannot be duplicated using Grafana datasources

### ISSUE THREAD

**Issue by john-r-swyftx** [prometheus-community/prom-label-proxy#191]
The suggested way to provide multiple values using http headers is:

```
You can provide multiple values for the label using several HTTP headers:

➜  ~ curl -H 'X-Tenant=something' -H 'X-Tenant=anything' http://127.0.0.1:8080/api/v1/query\?query="up"
{"status":"success","data":{"resultType":"vector","result":[]}}%
```

Grafana datasources do not support more than one http header with the same name being set.
![Screenshot 2024-02-20 at 4 01 52 pm](https://github.com/prometheus-community/prom-label-proxy/assets/137012569/14c2fbbd-7f9f-4e98-95c8-4dad7a70f713)

will just send one `THANOS_TENANT` header.

Grafana for Loki [allows the format - A|B](https://grafana.com/docs/loki/latest/operations/multi-tenancy/#multi-tenant-queries) for its tenant headers. Can this be supported with prom-label-proxy?

Or is there a way around this I haven't seen yet? I am trying to query across 2 tenants

**Comment by simonpasquier** [comment]
I assume that it will be fixed in the upcoming prom-label-proxy version, thanks to https://github.com/prometheus-community/prom-label-proxy/pull/223.

**Comment by john-r-swyftx** [comment]
Thank you
