### ISSUE TITLE
Build/fix GitHub releases and Docker images

### ISSUE THREAD

**Issue by Tom-Fawcett** [prometheus-community/prom-label-proxy#41]
Hey :slightly_smiling_face: 

I can't seem to find any recent GitHub releases or Docker images for this repo.

Looks like the CircleCI publish_master job has been [failing on the docker login](https://app.circleci.com/pipelines/github/prometheus-community/prom-label-proxy/24/workflows/4eec4bea-9f38-4f5e-9810-87df5af30d52/jobs/54/parallel-runs/0/steps/0-109) step.

I also noticed that [the Makefile mentions bind-exporter](https://github.com/prometheus-community/prom-label-proxy/blob/652a2d90c09f076448bd6777d17ae4f4c0f2dd05/Makefile#L22), which is presumably a mistake.

**Comment by lilic** [comment]
Thanks for the issue!

@simonpasquier if I remember you finished up the release transfer, do you mind having a look at the failing docker login, thanks!

**Comment by Tom-Fawcett** [comment]
Thanks for everyone's help with this :slightly_smiling_face:

Unfortunately it looks like CircleCI is still failing
