### ISSUE TITLE
Return error response in case of errors

### ISSUE THREAD

**Issue by bwplotka** [prometheus-community/prom-label-proxy#51]
Wonder if we are doing right think on error case :thinking: 

```
func (r *routes) query(w http.ResponseWriter, req *http.Request) {
	expr, err := parser.ParseExpr(req.FormValue("query"))
	if err != nil {
		return
	}

	e := NewEnforcer([]*labels.Matcher{
		{
			Name:  r.label,
			Type:  labels.MatchEqual,
			Value: mustLabelValue(req.Context()),
		},
	}...)
	if err := e.EnforceNode(expr); err != nil {
		return
	}

	q := req.URL.Query()
	q.Set("query", expr.String())
	req.URL.RawQuery = q.Encode()

	r.handler.ServeHTTP(w, req)
}
```

Shouldn't we do some http.Error at least? :thinking:

**Comment by simonpasquier** [comment]
I thought the same while reviewing your PR. Maybe @brancz @s-urbaniak have more insights?

**Comment by s-urbaniak** [comment]
I believe I stumbled across this quite some time ago and I agree it is non obvious what happens, but effectively currently a parser failure will:

- return http status code 200 (debatable)
- will return an empty body (debatable)
- will not execute an upstream query (good)

We could return StatusBadRequest (400) instead, wdyt?

But somehow I have a dejavu as I am sure I asked this question OOB to @brancz :smile:

**Comment by brancz** [comment]
Error on parsing should be a 400, error on enforcing should be a 500 I think.

**Comment by jan--f** [comment]
Does #67 (at least partially) address this?
