### ISSUE TITLE
Grafana alert is not working as expected with Prom-Label-Proxy

### ISSUE THREAD

**Issue by anoop2503** [prometheus-community/prom-label-proxy#55]
Grafana alert evaluation is not happening correctly when using Prom-Label-Proxy.

Current architecture:
Grafana -> nginx -> prom-label-proxy -> cortex frontend -> thanos querier -> Prometheus

**Issue:**
Using nginx to add the label and value as query param in every requests. This is working for all dashboards and the data is showing correctly. However, the alert evaluation is not happening correctly and always showing in alerting status.

When I click the "Test Rule" from Grafana alert configuration, I can see the below error response.
```
Object
firing:true
state:"pending"
conditionEvals:" = true"
timeMs:"62.522ms"
error:"tsdb.HandleRequest() error server_error: server error: 502"
logs:Array[1]
0:Object
message:"Condition[0]: Query"
data:Object
```

**Comment by hanjm** [comment]
I am occur same issue and have solved it，then i will submit a pull request.

**Comment by m-yosefpor** [comment]
@anoop2503
can you please also share the sample nginx config which you are doing this please?
