### ISSUE TITLE
Query fails with sum(irate(query_here[interval:resolution]))

### ISSUE THREAD

**Issue by IbraheemAlSaady** [prometheus-community/prom-label-proxy#58]
Trying to run this query `sum(irate(container_network_receive_bytes_total{cluster="workload-1"}[4h:1h])) by (pod)` but its not working 

Grafana error: `Cannot read property 'result' of undefined`

Here is the request endpoint

```
/api/datasources/proxy/3/api/v1/query_range?query=sum(irate(container_network_receive_bytes_total%7Bcluster%3D%22workload-1%22%7D%5B4h%3A1h%5D))&start=1613397765&end=1613401365&step=15&namespace=monitoring
```

From Grafana, that is actually returning a 200 response, but the body is empty.

However, running this works just fine `sum(irate(container_network_receive_bytes_total{cluster="workload-1"}[4h])) by (pod)`

The difference is `[4h:1h]` in the first query vs `[4h]` in the second query 

Any idea why?

**Comment by simonpasquier** [comment]
Closing for now. Feel free to reopen if you can reproduce with the latest version.
