### ISSUE TITLE
/api/v2/alerts/groups

### ISSUE THREAD

**Issue by kfox1111** [prometheus-community/prom-label-proxy#89]
Trying to get alert-manager's ui to work. silences mostly work but seeing what alerts currently are firing and what alerts would match a new silence would be great. it seems to be trying to access /api/v2/alerts/groups which I don't think is supported. And it would need filtering, so just passing it through seems wrong. Is there a plan to support this?

**Comment by simonpasquier** [comment]
We would definitely welcome a contribution to support this new endpoint.

**Comment by prashbnair** [comment]
I will pick this up.

**Comment by simonpasquier** [comment]
Closed by #96
